import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <header>
          <Link href={`/`}>index</Link>
          <br />
          <Link href={`/search`}>search</Link>
          <br />
          <Link href={`/book/1`}>book/1</Link>
        </header>
        <main>{children}</main>
        <footer>푸터영역</footer>
      </body>
    </html>
  );
}
